apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: taibaton/ltw:latest
        ports:
        - containerPort: 8080
        # --- THÊM ĐOẠN DƯỚI ĐÂY VÀO ---
        env:
           - name: DB_URL
              value: "jdbc:mysql://terraform-20260524154609304100000005.chom4aao050k.ap-southeast-1.rds.amazonaws.com:3306/qlbh?useSSL=false"
            - name: DB_USER
              value: "admin" # Tên user bạn đã cấu hình trong terraform
            - name: DB_PASSWORD
              value: "Tai123456789" # Mật khẩu bạn đã set
